# Generated by Django 3.2 on 2021-07-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='mail',
            field=models.EmailField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
